export const OrderData = [
	{ number: "js0223002", unit: "高投芯未半导体有限公司", place: "四川省成都市", state: true },
	{ number: "js0223006", unit: "成都森未科技有限公司", place: "四川省成都市", state: true },
	{ number: "js0223015", unit: "电子科技大学", place: "四川省成都市", state: true },
	{ number: "js0223011", unit: "成都通量科技有限公司", place: "四川省成都市", state: true },
	{ number: "js0223008", unit: "成都复锦功率半导体技术发展有限公司", place: "四川省成都市", state: true },
	{ number: "js0223003", unit: "深圳市楠菲微电子有限公司 ", place: "广东省深圳市", state: true },
	{ number: "js0223013", unit: "成都奕成科技股份有限公司", place: "四川省成都市", state: true },
	{ number: "js0223012", unit: "成都探芯科技有限公司", place: "四川省成都市", state: true },
	{ number: "js0224005", unit: "西安紫光国芯半导体股份有限公司", place: "陕西省西安市", state: true },
	{ number: "js0224011", unit: "成都华微电子科技有限公司", place: "四川省成都市", state: true },
	{ number: "js0224008", unit: "晶艺半导体有限公司", place: "四川省成都市", state: true },
	{ number: "js0224009", unit: "重庆芯联半导体有限责任公司", place: "重庆市", state: true },
].map((item, index) => ({ id: index, ...item }));

export const OrderDataV2 = [
	{ name: "频谱分析仪", num: "SPECTRANV6PLUS", state: 0, user: "芯火微测（成都）科技有限公司", time: "2023/10" },
	{ name: "示波器", num: "2612B", state: 0, user: "芯火微测（成都）科技有限公司", time: "2023/10" },
	{ name: "示波器", num: "2612B", state: 0, user: "成都探芯科技有限公司", time: "" },
	{ name: "光隔离探头", num: "TIVP02", state: 1, user: "", time: "" },
	{
		name: "矢量网络分析测试系统",
		num: "VNA5000A",
		state: 0,
		user: "四川XXX电子科技有限公司（涉密）",
		time: "2024/05",
	},
	{ name: "示波器", num: "MSO58B5-BW-2000", state: 0, user: "芯火微测（成都）科技有限公司", time: "2023/10" },
	{ name: "6寸晶圆高频探针系统", num: "MPS150SV等", state: 1, user: "", time: "" },
	{ name: "网络攻击仪", num: "ThreatEX2900", state: 1, user: "", time: "" },
	{ name: "音频分析仪", num: "2722", state: 1, user: "", time: "" },
	{ name: "逻辑分析仪", num: "16804A", state: 1, user: "", time: "" },
	{ name: "示波器", num: "DP04104+TAP1500", state: 0, user: "芯火微测（成都）科技有限公司", time: "2023/10" },
	{ name: "源表", num: "2430", state: 1, user: "", time: "" },
	{ name: "抗静电功能测试仪", num: "SKS-0220", state: 1, user: "", time: "" },
	{ name: "信号源（信号发生器）", num: "33250A", state: 1, user: "", time: "" },
	{ name: "信号源", num: "34405A", state: 1, user: "", time: "" },
	{ name: "信号源(信号发生器)", num: "33220A", state: 1, user: "", time: "" },
	{ name: "示波器", num: "TDS2022B", state: 0, user: "成都探芯科技有限公司", time: "2023/10" },
	{ name: "ESD静电测试", num: "FMX-003", state: 1, user: "", time: "" },
	{ name: "数字万用表", num: "8845A", state: 1, user: "", time: "" },
	{ name: "电源1", num: "PPT-3615G", state: 1, user: "", time: "" },
	{ name: "电源2", num: "PPT-3615G", state: 1, user: "", time: "" },
	{ name: "晶体管图示仪", num: "DW4822", state: 1, user: "", time: "" },
	{ name: "程控电源1", num: "LPS-305", state: 1, user: "", time: "" },
	{ name: "程控电源2", num: "LPS-305", state: 1, user: "", time: "" },
	{ name: "直流电源1", num: "GPS-4303", state: 1, user: "", time: "" },
	{ name: "直流电源2", num: "GPS-4303", state: 1, user: "", time: "" },
	{ name: "直流电源3", num: "GPS-4303", state: 1, user: "", time: "" },
	{ name: "直流电源4", num: "GPS-4303", state: 1, user: "", time: "" },
	{ name: "直流电源5", num: "GPS-4303", state: 1, user: "", time: "" },
];
